global using System;
global using System.IO;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using LiveChartsCore;
global using LiveChartsCore.SkiaSharpView;
global using System.ComponentModel;
global using System.Windows.Threading;
global using LiveChartsCore.Defaults;
global using System.Collections.ObjectModel;
global using LiveChartsCore.SkiaSharpView.Painting;
global using SkiaSharp;
global using LiveChartsCore.Drawing;
global using System.Windows;
global using CommunityToolkit.Mvvm.ComponentModel;
global using System.Globalization;
global using System.Windows.Controls;
global using LiveChartsCore.Measure;
global using LiveChartsCore.Kernel.Sketches;
global using Statisitsche_Temp_Erfassung.Models;
global using MenuItem = Statisitsche_Temp_Erfassung.Models.MenuItem;
global using Statisitsche_Temp_Erfassung.Enums;
global using Statisitsche_Temp_Erfassung.Handlers;
global using System.Windows.Input;
global using JsonSerializer = System.Text.Json.JsonSerializer;
global using System.Net.Http;

